[package]
name = "hypertop"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Michael Ekstrand <md@ekstrandom.net>"]
description = "System usage monitor inspired by glances."

[dependencies]
anyhow = "~1.0"
log = "~0.4"
fern = "~0.6"
friendly = "~0.1"
clap = { version = "~4.4", features = ["derive"] }
ratatui = "~0.24"
sysinfo = { version = "~0.29", default-features = false }
